[package]
name = "seedctl-sol"
description.workspace = true
repository.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
seedctl-core.workspace = true

hex.workspace = true
bip39.workspace = true
ed25519-dalek.workspace = true
ed25519-hd-key.workspace = true
bs58.workspace = true

dialoguer.workspace = true
console.workspace = true
serde_json.workspace = true
reqwest.workspace = true
