[package]
name = "seedctl-xmr"
description.workspace = true
repository.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
seedctl-core.workspace = true
hex.workspace = true
bip39.workspace = true
console.workspace = true
dialoguer.workspace = true
serde_json.workspace = true
reqwest.workspace = true
sha3.workspace = true
curve25519-dalek.workspace = true
ed25519-hd-key.workspace = true
