#!/usr/bin/env sh
# To use, run the following command only once in the project directory:
#   git config core.hooksPath hooks

echo "[seedctl] Running checks..."

# ----- Checks -----
if ! make check; then
  echo "[seedctl] Checks failed. Commit aborted."
  exit 1
fi

echo "[seedctl] OK"
exit 0
