[package]
name = "seedctl-btc"
description.workspace = true
repository.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
# seedctl dependencies (crates)
seedctl-core.workspace = true
# Own dependencies
bitcoin.workspace = true
bip39.workspace = true
hex.workspace = true
# Global dependencies
dialoguer.workspace = true
console.workspace = true
serde_json.workspace = true
reqwest.workspace = true
