[package]
name = "seedctl-btc"
version.workspace = true
edition.workspace = true

[dependencies]
# seedctl dependencies (crates)
seedctl-core.workspace = true
# Own dependencies
bitcoin = { version = "0.32.8", features = ["base64"] }
bip39 = "2"
hex.workspace = true
# Global dependencies
dialoguer.workspace = true
console.workspace = true
serde_json.workspace = true
reqwest.workspace = true
